name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cloud-mail-db"
database_id = "4dc8a98e-d99c-4b72-a3a4-c8a3e4d4421b"

[[kv_namespaces]]
binding = "kv"
id = "4adfd9e29efb4a7090cdbc2afc4fcf1d"

[[r2_buckets]]
binding = "r2"
bucket_name = "cloud-mail-r2"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 * * * *"]
# trigger rebuild

[vars]
domain = ["dfmsolutions.de"]
admin = "info@dfmsolutions.de"
jwt_secret = "e392bdf3dc8e866633d31c2fcb9c3b2e5b5220a375a055ec8ee483575dab3f1b"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
